### ISSUE TITLE
[BUG] Button to send requests is broken !

### ISSUE THREAD

**Issue by PyyLog** [ipsa-scrypt/big-brain#14]
When clicking on the button, nothing happens.
[The expected behaviour is that after triggering the button, the output is displayed.]

<img width="925" alt="image" src="https://github.com/ipsa-scrypt/big-brain/assets/78143876/2cf71988-5e99-4766-89da-7f3aa8ec3476">

**Comment by Arkozzz** [comment]
The problem is probably due to the position of the history that is always displayed (but in transparent when it is hide).
The problem class is "history-div history-div-disappear".
![BIGBRAINBUG](https://github.com/ipsa-scrypt/big-brain/assets/93744170/0f60310c-6287-4ead-af16-46dd2979d190)

**Comment by PyyLog** [comment]
Oh nice ! Didn't thought about this at all... I will try that asap 😉.

**Comment by PyyLog** [comment]
@Arkozzz Aren't you a big 🧠 by any chance ?_
Well played !! This was the issue.
<img width="956" alt="image" src="https://github.com/ipsa-scrypt/big-brain/assets/78143876/680bdd83-6201-4b0e-9532-aed70fc43502">

I moved the history-div to a place where it doesn't overlap with the form compoment. Everything now works !
